name: CI - Robocode, Checkstyle e SpotBugs com relatório

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ROBOTS_JAVA_DIR: src

jobs:
  qualidade_e_seguranca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          
      # CHECKSTYLE E SPOTBUGS
      - name: Baixar Checkstyle
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar -O checkstyle.jar
      - name: Rodar Checkstyle e salvar status
        run: |
          mkdir -p battle_logs
          set +e 
          java -jar checkstyle.jar -c libs/google_checks.xml $ROBOTS_JAVA_DIR/*.java
          echo $? > battle_logs/checkstyle_status.txt
          set -e
      - name: Baixar e extrair SpotBugs
        run: |
          wget https://repo1.maven.org/maven2/com/github/spotbugs/spotbugs/4.8.3/spotbugs-4.8.3.tgz -O spotbugs.tgz
          tar -xzf spotbugs.tgz
          chmod +x spotbugs-4.8.3/bin/spotbugs
      - name: Compilar robôs para SpotBugs
        run: |
          mkdir -p classes
          javac -cp "libs/*" -d classes $ROBOTS_JAVA_DIR/*.java
      - name: Rodar SpotBugs e salvar status
        run: |
          set +e
          spotbugs-4.8.3/bin/spotbugs -textui -effort:min -output battle_logs/spotbugs.txt classes
          echo $? > battle_logs/spotbugs_status.txt
          set -e

      - name: Compilar robôs para a batalha e salvar status
        run: |
          mkdir -p robocode/robots/
          # Compila cada arquivo a partir do seu diretório raiz (src)
          # para forçar a criação da estrutura de pacotes no destino.
          javac -cp "libs/*" -d robocode/robots/ src/TrystanBot.java src/Corners.java
          echo $? > battle_logs/robocode_build_status.txt
      
      - name: DEBUG - Listar arquivos compilados
        run: |
          echo "================================================="
          echo "Conteúdo da pasta robocode/robots:"
          ls -R robocode/robots
          echo "================================================="

      # GERAR RELATÓRIO
      - name: Gerar Relatório da Batalha
        run: |
          chmod +x scripts/testar_batalha.sh
          bash scripts/testar_batalha.sh

      # UPLOAD DO ARTEFATO
      - name: Upload battle logs (com relatório)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-batalha
          path: battle_logs/